package api

//	type AutoGenerated struct {
//		Status    string  `json:"status"`
//		RequestID string  `json:"request_id"`
//		Results   Results `json:"results"`
//	}
//
// type Address struct {
// 	Address1   string `json:"address1"`
// 	City       string `json:"city"`
// 	PostalCode string `json:"postal_code"`
// 	State      string `json:"state"`
// }

//	type Branding struct {
//		LogoURL string `json:"logo_url"`
//		IconURL string `json:"icon_url"`
//	}
type Results struct {
	Active bool `json:"active"`
	// Address                     Address   `json:"address"`
	// Branding                    Branding  `json:"branding"`
	// Cik           string `json:"cik"`
	// CompositeFigi string `json:"composite_figi"`
	CurrencyName string `json:"currency_name"`
	// DelistedUtc                 time.Time `json:"delisted_utc"`
	// Description string `json:"description"`
	HomepageURL string `json:"homepage_url"`
	// LastUpdatedUtc              time.Time `json:"last_updated_utc"`
	// ListDate                    string `json:"list_date"`
	// Locale                      string `json:"locale"`
	// Market                      string `json:"market"`
	MarketCap int64  `json:"market_cap"`
	Name      string `json:"name"`
	// PhoneNumber                 string `json:"phone_number"`
	// PrimaryExchange             string `json:"primary_exchange"`
	// ShareClassFigi              string `json:"share_class_figi"`
	// ShareClassSharesOutstanding int    `json:"share_class_shares_outstanding"`
	// SicCode                     string `json:"sic_code"`
	// SicDescription              string `json:"sic_description"`
	Ticker string `json:"ticker"`
	// TickerRoot                  string `json:"ticker_root"`
	// TotalEmployees              int    `json:"total_employees"`
	// Type                        string `json:"type"`
	// WeightedSharesOutstanding   int    `json:"weighted_shares_outstanding"`
}
