package api

//	type AutoGenerated struct {
//		Status    string  `json:"status"`
//		RequestID string  `json:"request_id"`
//		Results   Results `json:"results"`
//	}
//
// type Address struct {
// 	Address1   string `json:"address1"`
// 	City       string `json:"city"`
// 	PostalCode string `json:"postal_code"`
// 	State      string `json:"state"`
// }

//	type Branding struct {
//		LogoURL string `json:"logo_url"`
//		IconURL string `json:"icon_url"`
//	}

type Results struct { // from polygon Ticker model
	Active bool `json:"active"`
	// Address                     CompanyAddress `json:"address,omitempty"`
	// Branding                    Branding       `json:"branding,omitempty"`
	// CIK                         string         `json:"cik,omitempty"`
	// CompositeFIGI               string         `json:"composite_figi,omitempty"`
	CurrencyName       string `json:"currency_name,omitempty"`
	CurrencySymbol     string `json:"currency_symbol,omitempty"`
	BaseCurrencyName   string `json:"base_currency_name,omitempty"`
	BaseCurrencySymbol string `json:"base_currency_symbol,omitempty"`
	// DelistedUTC        Time   `json:"delisted_utc,omitempty"`
	Description string `json:"description,omitempty"`
	HomepageURL string `json:"homepage_url,omitempty"`
	// ListDate                    Date           `json:"list_date,omitempty"`
	// Locale                      string         `json:"locale,omitempty"`
	// Market                      string         `json:"market,omitempty"`
	MarketCap float64 `json:"market_cap,omitempty"`
	Name      string  `json:"name,omitempty"`
	// PhoneNumber                 string         `json:"phone_number,omitempty"`
	// PrimaryExchange             string         `json:"primary_exchange,omitempty"`
	// ShareClassFIGI              string         `json:"share_class_figi,omitempty"`
	// ShareClassSharesOutstanding int64          `json:"share_class_shares_outstanding,omitempty"`
	// SICCode                     string         `json:"sic_code,omitempty"`
	// SICDescription              string         `json:"sic_description,omitempty"`
	Ticker string `json:"ticker,omitempty"`
	// TickerRoot                  string         `json:"ticker_root,omitempty"`
	// TickerSuffix                string         `json:"ticker_suffix,omitempty"`
	// TotalEmployees              int32          `json:"total_employees,omitempty"`
	// Type                        string         `json:"type,omitempty"`
	WeightedSharesOutstanding int64 `json:"weighted_shares_outstanding,omitempty"`
	// SourceFeed                  string         `json:"source_feed,omitempty"`
}
